### PR TITLE
Add Thing Model support

### PR DESCRIPTION
**Pull request by fatadel**

### CODE REVIEW

**Comment by egekorkan** [comment]
It seems you need to adjust the playwright tests @fatadel

**Comment by fatadel** [comment]
> It seems you need to adjust the playwright tests @fatadel

Done ✅

**Comment by egekorkan** [comment]
We can merge once the tests are through. Otherwise, anything left to do?

**Comment by fatadel** [comment]
> We can merge once the tests are through. Otherwise, anything left to do?

TM examples, but I can add them in a separate PR. What do you think?

**Comment by egekorkan** [comment]
> > We can merge once the tests are through. Otherwise, anything left to do?
> 
> TM examples, but I can add them in a separate PR. What do you think?

Ah yes, please do them all here :)

**Comment by fatadel** [comment]
> > > We can merge once the tests are through. Otherwise, anything left to do?
> > 
> > 
> > TM examples, but I can add them in a separate PR. What do you think?
> 
> Ah yes, please do them all here :)

Done 😊

**Comment by egekorkan** [comment]
@fatadel could you fix the `@context` values of the examples as well? Also, I have just realized that auto validate does not work in TM view but it does in the TD view

**Comment by fatadel** [comment]
@egekorkan Should be done now.

**Comment by egekorkan** [comment]
Thank you @fatadel !

**Pull request merged**
