### PR TITLE
update td-vocab-title--DataSchema.json based on td-vocab-description--DataSchema.json

### PR DESCRIPTION
**Pull request by yamagile**
Some of the assertions at risk (td-data-schema_title and td-vocab-title--DataSchema) should be "pass".

### CODE REVIEW

**Comment by mmccool** [comment]
Yeah, that looks like a bug, as I suspected.  Thanks for the patch.   Unfortunately I can't merge, only Ege has write access.

**Comment by egekorkan** [comment]
Thank you for your PR, it made me realise that td-vocab-description--DataSchema is wrong as well. I will update that as well

**Comment by yamagile** [comment]
@egekorkan Thank you for your review and in advance for your updates. I'll close this PR.

**Comment by egekorkan** [comment]
It is now fixed in #89

**Pull request closed without merging**
