### PR TITLE
upgrade ajv, add ajv-formats, update all schemas to version 0.7

### PR DESCRIPTION
**Pull request by FadySalama**

### CODE REVIEW

**Comment by egekorkan** [comment]
Failure seems to be at ID: Error: strict mode: unknown keyword: "$schema " for the assertions package

**Comment by egekorkan** [comment]
The PR should be made to the v1.1 branch otherwise there are too many changes. Is it intended to be made here?

**Comment by FadySalama** [comment]
The intention was to make them here, as this is actually one small change applied to all schemas and does not change or break the behavior of the code. I am also reassessing the structure of the code in the v1.1 Branch.

**Comment by egekorkan** [comment]
I see now, let's go! :)

**Pull request merged**
