### PR TITLE
update TD and TM Schemas

### LINKED ISSUE #255: Syncing with the new JSON Schema
We are out of date with the schemas in the TD spec for TM and TD.

### PR DESCRIPTION
**Pull request by FadySalama**
Fixes #255

### CODE REVIEW

**Comment by FadySalama** [comment]
> https://github.com/thingweb/thingweb-playground/blob/master/packages/core/td-schema-full.json also needs to be updated since that checks for presence of defaults. I forgot to mention it in the issue

Is there a way to do it automatically?

**Comment by FadySalama** [comment]
> > > https://github.com/thingweb/thingweb-playground/blob/master/packages/core/td-schema-full.json also needs to be updated since that checks for presence of defaults. I forgot to mention it in the issue
> > 
> > 
> > Is there a way to do it automatically?
> 
> Nope but it is simply syncing with https://w3c.github.io/wot-thing-description/#sec-default-values

I updated the full schema. However, I also committed the updates to the manual.csv scripts on the same branch before realizing that this branch is the one being merged in this PR. @egekorkan Should we simply merge?

**Review by egekorkan — APPROVED** [review]

**Comment by egekorkan** [comment]
@FadySalama the test is failing though

**Comment by FadySalama** [comment]
> @FadySalama the test is failing though

Fixed and merging

**Pull request merged**
